# Generated by Django 5.0.1 on 2024-01-23 13:25

import django.db.models.deletion
import merchants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, validators=[merchants.models.validate_address], verbose_name='Address')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.trader', verbose_name='Trader')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
